services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - PORT=3009
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$$PORT/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
